version: "3.7"
services:
  logstash:
    image: netsage/pipeline_logstash:latest
  ## If you need to allocate more than 1GB (default) override the JMV options
  #    volumes:
  #      - ./userConfig/jvm.options:/usr/share/logstash/config/jvm.options
